#############################################################################
#    ATTENTION!                                                             #
#    This code is automatically generated by flatdata generator.            #
#    Any modifications to this file will be lost upon next regeneration.    #
#############################################################################

import flatdata




class n_U8(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct U8
{
    f : u8 : 8;
}
}

"""
    _SIZE_IN_BITS = 8
    _SIZE_IN_BYTES = 1
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=8, is_signed=False, dtype="B"),
    }
    _FIELD_KEYS = {
        "f",
    }

class n_I8(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct I8
{
    f : i8 : 8;
}
}

"""
    _SIZE_IN_BITS = 8
    _SIZE_IN_BYTES = 1
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=8, is_signed=True, dtype="b"),
    }
    _FIELD_KEYS = {
        "f",
    }

class n_U16(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct U16
{
    f : u16 : 16;
}
}

"""
    _SIZE_IN_BITS = 16
    _SIZE_IN_BYTES = 2
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=16, is_signed=False, dtype="u2"),
    }
    _FIELD_KEYS = {
        "f",
    }

class n_I16(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct I16
{
    f : i16 : 16;
}
}

"""
    _SIZE_IN_BITS = 16
    _SIZE_IN_BYTES = 2
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=16, is_signed=True, dtype="i2"),
    }
    _FIELD_KEYS = {
        "f",
    }

class n_U32(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct U32
{
    f : u32 : 32;
}
}

"""
    _SIZE_IN_BITS = 32
    _SIZE_IN_BYTES = 4
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=32, is_signed=False, dtype="u4"),
    }
    _FIELD_KEYS = {
        "f",
    }

class n_I32(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct I32
{
    f : i32 : 32;
}
}

"""
    _SIZE_IN_BITS = 32
    _SIZE_IN_BYTES = 4
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=32, is_signed=True, dtype="i4"),
    }
    _FIELD_KEYS = {
        "f",
    }

class n_U64(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct U64
{
    f : u64 : 64;
}
}

"""
    _SIZE_IN_BITS = 64
    _SIZE_IN_BYTES = 8
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=64, is_signed=False, dtype="u8"),
    }
    _FIELD_KEYS = {
        "f",
    }

class n_I64(flatdata.structure.Structure):
    """"""
    _SCHEMA = """namespace n {
struct I64
{
    f : i64 : 64;
}
}

"""
    _SIZE_IN_BITS = 64
    _SIZE_IN_BYTES = 8
    _FIELDS = {
        "f": flatdata.structure.FieldSignature(offset=0, width=64, is_signed=True, dtype="i8"),
    }
    _FIELD_KEYS = {
        "f",
    }
