// Do not edit: This code was generated by flatdata's generator.
pub mod n {

pub mod schema {
pub mod structs {
}

}    // This is a comment about foo
pub const FOO: u32 = 0;
    /// This is a comment about bar
pub const BAR: u64 = 0;
}
