// Do not edit: This code was generated by flatdata's generator.
pub mod n {

pub mod schema {
pub mod structs {
}

}pub const FOO: i8 = 0;
}

pub mod m {

pub mod schema {
pub mod structs {
}

}pub const FOO: i8 = 1;
}
