// Do not edit: This code was generated by flatdata's generator.
/// This test tests that symbols are properly separated into namespaces
pub mod n {

#[doc(hidden)]
pub mod schema {
pub mod structs {
}

}
pub const FOO: i8 = 0;
}

/// This test tests that symbols are properly separated into namespaces
pub mod m {

#[doc(hidden)]
pub mod schema {
pub mod structs {
}

}
pub const FOO: i8 = 1;
}
