// Do not edit: This code was generated by flatdata's generator.
pub mod n {

pub mod schema {
pub mod structs {
pub const FOO: &str = r#"namespace n {
struct Foo
{
    f : u32 : 32;
}
}

"#;}}

define_struct!(
    Foo,
    RefFoo,
    RefMutFoo,
    schema::structs::FOO,
    4,
    (f, set_f, u32, u32, 0, 32));
}

pub mod m {

pub mod schema {
pub mod structs {
pub const FOO: &str = r#"namespace m {
struct Foo
{
    f : u32 : 32;
}
}

"#;}}

define_struct!(
    Foo,
    RefFoo,
    RefMutFoo,
    schema::structs::FOO,
    4,
    (f, set_f, u32, u32, 0, 32));
}
