name: flatdata-dot
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLORS: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: sudo apt-get install graphviz
      - name: Generator
        run: pip3 install ./flatdata-generator
      - name: Build and Test
        run: |
           ci/dot_test_cases.sh
