name: flatdata-generator
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLORS: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        uses: astral-sh/setup-uv@v6
      - name: Run tests
        run: |
          cd flatdata-generator
          uv run --with pytest pytest -v
          pip install .
          flatdata-generator --help