name: flatdata-py
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLORS: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        uses: astral-sh/setup-uv@v6
      - name: Run tests
        run: |
          cd flatdata-py
          uv venv
          uv pip install ../flatdata-generator
          uv pip install ".[inspector]" pytest mypy
          .venv/bin/pytest -v
          .venv/bin/flatdata-inspector --help
      - name: Type check
        run: |
          cd flatdata-py
          .venv/bin/mypy flatdata/

